# Python (data science) - Pandas

_Mikołaj Leszczuk_

## Pandas

Kolejną biblioteką którą poznamy będzie Pandas. Pandas to pakiet zbudowany na bazie NumPy który dostarcza nam obiekty typu `DataFrame`, które są wielowymiarowymi tabelami z indeksami dla kolumn i wierszy. Poznamy dzisiaj w jaki sposób korzystać z abstrakcji dostarczanych przez Pandas i jak pracować z obiektami będacymi częścią tego pakietu.


- Pandas to potężna biblioteka open-source służąca do manipulacji i analizy danych w języku Python.
- Została po raz pierwszy wydana w 2008 roku przez Wes McKinney i obecnie jest utrzymywana przez zespół programistów.
- Nazwa "Pandas" pochodzi od "Panel Data", co odnosi się do wielowymiarowych zestawów danych, z którymi Pandas jest projektowany do pracy.

- Pandas zapewnia struktury danych umożliwiające efektywną pracę z danymi opisanymi etykietami i relacyjnymi, takimi jak Series (1D) i DataFrame (2D).
- Jest szeroko stosowany w dziedzinach takich jak data science, uczenie maszynowe, finanse i inne, gdzie wymagana jest analiza danych.
- Niektóre z popularnych funkcji Pandas obejmują czyszczenie danych, filtrowanie, sortowanie, grupowanie, łączenie i zmianę kształtu.
- Pandas integruje się z innymi bibliotekami Pythona, takimi jak NumPy, Matplotlib i SciPy, aby zapewnić kompleksowy zestaw narzędzi do analizy danych.

Zaczniemy od zaimportowania pakietu:

In [1]:
import pandas as pd
import numpy as np

### Series

`Series` jest jednowymiarową tablicą danych z indeksem, można go stworzyć z listy lub tabeli:

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

`index` jest typu `pd.Index`, o którymi opowiem za chwilę:

In [3]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)

In [4]:
print(type(data.index))

<class 'pandas.core.indexes.range.RangeIndex'>

`values` jest zwykłą numpy tablicą reprezentująca wartości danego `Series`:

In [5]:
print(data.values)

[0.25 0.5  0.75 1.  ]

In [6]:
print(type(data.values))

<class 'numpy.ndarray'>

Podstawową różnicą między `Series` a zwykłą tablicą, jest fakt, że możemy sami w nim ustalić indeks:

In [7]:
data = pd.Series(      [0.25, 0.5, 0.75, 1.0],
                 index=['a',  'b', 'c',  'd'])  # ustalamy indeks jako obiekty typu `str`
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

np.float64(0.5)

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])  # indeksy są liczbami,
                                      # ale nie muszą mieć konkretnej kolejności
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

Tak jak tablice w NumPy reprezentują kolekcje pojedynczego typu co pomaga nam wykonywać pewne operacje szybciej, podobnie `Series` możemy rozumieć jako implementacje mapy (słownika) zawierającej wartości tego samego typu:

In [10]:
population_dict = {'California': 38332521,
                   'Texas'     : 26448193,
                   'New York'  : 19651127,
                   'Florida'   : 19552860,
                   'Illinois'  : 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [11]:
population['California']

np.int64(38332521)

Jednak wciąż możemy korzystać z operacji typowych dla tablic jak np. slice:

In [12]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

Obiekty typu `Series` możemy tworzyć na różne sposoby:

In [13]:
pd.Series([2, 4, 6])  # z listy

0    2
1    4
2    6
dtype: int64

In [14]:
pd.Series(5, index=[1, 2, 3])  # jako jedna wartość, która jest powtarzana dla indeksów

1    5
2    5
3    5
dtype: int64

In [15]:
pd.Series({2: 'a', 1: 'b', 3: 'c'})  # ze słownika

2    a
1    b
3    c
dtype: object

In [16]:
pd.Series(np.arange(10))  # z tablicy numpy

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

### DataFrame

`DataFrame` jest analogią do dwuwymiarowej tablicy NumPy, która ma dowolnie zdefiniowany indeks zarówno dla wierszy i kolumn. `DataFrame` jest kolekcją obiektów typu `Series` o wspólnym indeksie:

In [17]:
area_dict = {'California': 423967,
             'Texas'     : 695662,
             'New York'  : 141297,
             'Florida'   : 170312,
             'Illinois'  : 149995,
            'Washington' : 184000
            }
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Washington    184000
dtype: int64

Zauważ jak obiekt typu `DataFrame` powstaje przez przekazanie słownika którego klucze są nazwami kolumn, a wartościami są obiekty typu `Series`:

In [18]:
states = pd.DataFrame({
    'population': population,
    'area'      : area
})  # Tworzymy obiekt typu `DataFrame`
states

            population    area
California  38332521.0  423967
Florida     19552860.0  170312
Illinois    12882135.0  149995
New York    19651127.0  141297
Texas       26448193.0  695662
Washington         NaN  184000

`DataFrame` posiada atrybut `index` który dostarcza nam indeksy wierszy, oraz atrybut `columns` który dostarcza indeksy kolumn.

In [19]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas', 'Washington'], dtype='object')

In [20]:
states.columns

Index(['population', 'area'], dtype='object')

Tworzenie obiektów typu `DataFrame`:

In [21]:
pd.DataFrame(population, columns=['population'])  # z jednego `Series`

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [22]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(data)
pd.DataFrame(data)  # z listy słowników

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

   a  b
0  0  0
1  1  2
2  2  4

In [23]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])  # pandas sam wypełni brakujące indeksy

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [24]:
pd.DataFrame({
    'population': population,
    'area': area
})  # słownik `Series`

            population    area
California  38332521.0  423967
Florida     19552860.0  170312
Illinois    12882135.0  149995
New York    19651127.0  141297
Texas       26448193.0  695662
Washington         NaN  184000

In [27]:
pd.DataFrame(
    np.random.rand(3, 2),
    columns=['foo', 'bar'],
    index=['a', 'b', 'c']    
)  # z dwuwymiarowej tablicy numpy

        foo       bar
a  0.333584  0.422866
b  0.288047  0.378376
c  0.997084  0.238999

### Index

`Index` bardzo przypomina tablicę numpy z tą różnicą, że obiekty typu `Index` są niemutowalne:

In [28]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

Metoda `reset_index(inplace=True)` w Pandas służy do zresetowania indeksu DataFrame’u:

In [29]:
states.reset_index(inplace=True)
states

        index  population    area
0  California  38332521.0  423967
1     Florida  19552860.0  170312
2    Illinois  12882135.0  149995
3    New York  19651127.0  141297
4       Texas  26448193.0  695662
5  Washington         NaN  184000

### Indeksowanie i wybieranie danych

Ponieważ obiekty typu `Series` posiadają swój indeks, ale mogą być również indeksowane z użyciem domyślnego indeksu z numpy, musimy dobrze rozumieć kiedy korzystamy z którego indeksowania:

In [30]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [31]:
data[1]  # indeks typu `Series`

'a'

In [32]:
data[1:3]  # indeks z numpy

3    b
5    c
dtype: object

Aby lepiej wiedzieć kiedy korzystamy z którego indeksu istnieją atrybuty `loc` oraz `iloc`.

`loc` używa indeksu z `Series`:

In [33]:
data

1    a
3    b
5    c
dtype: object

In [34]:
data.loc[1]

'a'

In [35]:
data.loc[1:3]

1    a
3    b
dtype: object

`iloc` korzysta z indeksów tablicy numpy

In [36]:
data

1    a
3    b
5    c
dtype: object

In [37]:
data.iloc[1]

'b'

In [38]:
data.iloc[1:3]

3    b
5    c
dtype: object

### Wybieranie danych z DataFrame

Pierwszy sposób w jaki możemy wybierać dane z DataFrame, to traktując go jako słownik typu `Series`:

In [39]:
area = pd.Series({
    'California': 423967,   'Texas'  : 695662,
    'New York'  : 141297,   'Florida': 170312,
    'Illinois'  : 149995
})
pop = pd.Series({
    'California': 38332521, 'Texas'  : 26448193,
    'New York'  : 19651127, 'Florida': 19552860,
    'Illinois'  : 12882135
})
data = pd.DataFrame({'area':area, 'pop':pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [40]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [41]:
data['density'] = (data['pop'] / data['area'])
data['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

In [43]:
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

Z drugiej strony możemy myśleć o DataFrame jako o rozbudowanej dwuwymiarowej tablicy:

In [42]:
data.iloc[[0, 1, 2], [2, 1]]

               density       pop
California   90.413926  38332521
Texas        38.018740  26448193
New York    139.076746  19651127

In [44]:
data.loc[:'Florida','pop':'density']

                 pop     density
California  38332521   90.413926
Texas       26448193   38.018740
New York    19651127  139.076746
Florida     19552860  114.806121

In [45]:
data.iloc[0, 2] = 90

In [46]:
data

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Operowanie na brakujących danych w Pandas

W Pythonie brakujące wartości możemy reprezentować jako `None`, jednak ponieważ `None` jest singletonem (ma własny typ i istnieje tylko jeden obiekt typu `None`), to nie możemy go sprawnie używać w NumPy:

In [47]:
vals1 = np.array([1, None, 3, 4])

In [48]:
vals1

array([1, None, 3, 4], dtype=object)

In [ ]:
vals1.dtype

Ponieważ jedyny wspólny typ dla tych obiektów to typ `object`, wszystkie operacje będą wykonywane dla pojedynczych elementów i tracimy wektorowość.

`object` (bardzo wolno):

In [49]:
%timeit np.arange(2_000_000, dtype=object).sum()

35.6 ms ± 435 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

`int` (bardzo szybko):

In [50]:
%timeit np.arange(2_000_000, dtype=int).sum()

310 μs ± 721 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Nie możemy również korzystać z operacji liczbowych:

In [51]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

Innym sposobem reprezentacji brakujących danych liczbowych jest użycie `NaN` - _not a number_

In [52]:
vals2 = np.array([1, np.nan, 3, 4])

In [53]:
vals2

array([ 1., nan,  3.,  4.])

In [54]:
vals2.dtype

dtype('float64')

Dzięki temu zachowujemy liczbowy typ, jednak operacje liczbowe wciąż są źle zdefiniowane:

In [55]:
1 + np.nan

nan

In [56]:
vals2.sum()

np.float64(nan)

In [57]:
vals2.min()

np.float64(nan)

In [58]:
vals2.max()

np.float64(nan)

Korzystając z NumPy możemy użyć specjalnych funkcji omijających NaN:

In [59]:
vals2

array([ 1., nan,  3.,  4.])

In [60]:
np.nansum(vals2)

np.float64(8.0)

In [61]:
np.nanmin(vals2)

np.float64(1.0)

In [62]:
np.nanmax(vals2)

np.float64(4.0)

#### NaN i None w Pandas

Pandas traktuje `NaN` i `None` w ten sam sposób:

In [63]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

W Pandas mamy również specjalne metody które pozwalają nam znajdować, usuwać i wypełniać puste wartości:

In [64]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [65]:
data.isnull()  # znajdowanie pustych wartości

0    False
1     True
2    False
3     True
dtype: bool

In [66]:
data[data.notnull()]  # wybieranie niepustych wartości

0        1
2    hello
dtype: object

In [67]:
data.dropna()  # usuwanie pustych wartości

0        1
2    hello
dtype: object

In [68]:
data.fillna(0)  # wypełnianie pustych wartości

0        1
1        0
2    hello
3        0
dtype: object

### Łączenie DataFrame w Pandas

Funkcją służącą do łączenia `DataFrame` jest `pd.concat`, która w działaniu jest podobna do `np.concatenate`.

In [69]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])

In [70]:
ser1

1    A
2    B
3    C
dtype: object

In [71]:
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

In [72]:
ser2

4    D
5    E
6    F
dtype: object

In [75]:
pd.concat([ser1, ser2], axis=0)

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [76]:
def make_df(cols, ind):
    """Stwórz DataFrame z kombinacji cols i ind"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

In [77]:
# example DataFrame
make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [78]:
df1 = make_df('AB', [1, 2])

In [79]:
df1

    A   B
1  A1  B1
2  A2  B2

In [80]:
df2 = make_df('AB', [3, 4])

In [81]:
df2

    A   B
3  A3  B3
4  A4  B4

In [82]:
pd.concat([df1, df2], axis=0)  # łączenie po wierszach

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [83]:
pd.concat([df1, df2], axis=1)  # łączenie po kolumnach

     A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

Innym rodzajem łączenia DataFrame jaki możemy wykonywać są _joiny_ które możemy znać z SQL, joiny w Pandas wykonujemy z użyciem `pd.merge`.

In [84]:
df1 = pd.DataFrame({'employee': ['Bob',        'Jake',        'Lisa',        'Sue'],
                    'group'   : ['Accounting', 'Engineering', 'Engineering', 'HR' ]})

In [85]:
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [86]:
df2 = pd.DataFrame({'employee' : ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [ 2004,   2008,  2012,   2014]})

In [87]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [88]:
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

`pd.merge` samo rozpoznało wspólną kolumnę `employee` i połączyło tabele z jej użyciem.

Funkcja (właść. metoda) ta ignoruje również indeksy wejściowych data frame, chyba, że korzystamy z łączenia przez indeks.

In [89]:
df4 = pd.DataFrame({'group'     : ['Accounting', 'Engineering', 'HR'   ],
                    'supervisor': ['Carly',      'Guido',       'Steve']})

In [91]:
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [92]:
pd.merge(df3, df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [93]:
df5 = pd.DataFrame({
    'group' : [
        'Accounting',   
        'Accounting',
        'Engineering',  
        'Engineering',
        'H   R',           
        'H   R'],
    'skills': [
        'math',         
        'spreadsheets',
        'coding',       
        'linux',
        'spreadsheets', 
        'organization']
})

In [94]:
df5

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [95]:
combined_df=pd.merge(df1, df5)
combined_df

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

Jeżeli chcemy wprost powiedzieć po której kolumnie chcemy wykonać łączenie możemy podać ją przez parametr `on`:

In [96]:
pd.merge(df1, df2, on=['employee'])

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

Jeżeli tabele mają różne nazwy kolumn po których chcemy je połączyć możemy skorzystać z `left_on` i `right_on`

In [98]:
df3 = pd.DataFrame({
    'name': [
        'Bob',
        'Jake',
        'Lisa', 
        'Sue'],
    'salary': [
        70000,
        80000,
        120000,
        90000],
    'group': [
        70000,
        80000,
        120000,
        90000]

})
df3

   name  salary   group
0   Bob   70000   70000
1  Jake   80000   80000
2  Lisa  120000  120000
3   Sue   90000   90000

In [99]:
pd.merge(df1, df3, left_on="employee", right_on="name")

  employee      group_x  name  salary  group_y
0      Bob   Accounting   Bob   70000    70000
1     Jake  Engineering  Jake   80000    80000
2     Lisa  Engineering  Lisa  120000   120000
3      Sue           HR   Sue   90000    90000

Ponieważ taka tabela ma zbedną kolumnę, możemy ją usunąc przez `drop`:

In [ ]:
merged_df

In [100]:
pd.merge?

Rodzaj łączenia wybieramy przez parametr `how`.
Możliwe wartości dla tego parametru to:

- **left**
- **right**
- **outer**
- **inner**
- **cross**

In [102]:
df1 = make_df('AB', [1, 2, 4])

In [103]:
df1

    A   B
1  A1  B1
2  A2  B2
4  A4  B4

In [104]:
df2 = make_df('ABCD', [1, 2, 5, 6])

In [105]:
df2

    A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
5  A5  B5  C5  D5
6  A6  B6  C6  D6

Przykłady różnych typów operacji join...

`df1` **left** join `df2`:

In [106]:
pd.merge(df1, df2, on='A', how='left')

    A B_x  B_y    C    D
0  A1  B1   B1   C1   D1
1  A2  B2   B2   C2   D2
2  A4  B4  NaN  NaN  NaN

`df1` **right** join `df2`:

In [107]:
pd.merge(df1, df2, on='A', how='right')

    A  B_x B_y   C   D
0  A1   B1  B1  C1  D1
1  A2   B2  B2  C2  D2
2  A5  NaN  B5  C5  D5
3  A6  NaN  B6  C6  D6

`df1` **outer** join `df2`:

In [108]:
pd.merge(df1, df2, on='A', how='outer')

    A  B_x  B_y    C    D
0  A1   B1   B1   C1   D1
1  A2   B2   B2   C2   D2
2  A4   B4  NaN  NaN  NaN
3  A5  NaN   B5   C5   D5
4  A6  NaN   B6   C6   D6

`df1` **inner** join `df2`:

In [109]:
pd.merge(df1, df2, how='inner')

    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2

### Agregacja i grupowanie

Agregacje jakie domyślnie możemy stosować w Pandas są analogiczne do tych które występują w NumPy. Wywołanie agregacji na `DataFrame` zwraca wynik dla każdej kolumny:

In [110]:
df = pd.DataFrame({
    'A': np.random.rand(20),
    'B': np.random.rand(20)})
df

           A         B
0   0.901727  0.657349
1   0.584876  0.758500
2   0.569845  0.198778
3   0.382658  0.523863
4   0.718643  0.112744
5   0.523150  0.576394
6   0.923250  0.432503
7   0.986322  0.732586
8   0.479599  0.754302
9   0.015015  0.523764
10  0.910741  0.382970
11  0.307781  0.143653
12  0.971354  0.346224
13  0.963787  0.099155
14  0.087913  0.490556
15  0.841953  0.169827
16  0.016151  0.697598
17  0.483262  0.106001
18  0.592939  0.596152
19  0.118726  0.680885

In [111]:
#istotna metoda, takze jest agregacją
df.describe()

               A          B
count  20.000000  20.000000
mean    0.568985   0.449190
std     0.333226   0.238558
min     0.015015   0.099155
25%     0.363939   0.191540
50%     0.577360   0.507160
75%     0.903980   0.663233
max     0.986322   0.758500

In [112]:
df.mean()

A    0.568985
B    0.449190
dtype: float64

Inne agregacje jakie możemy wykonywać:

- `count()`
- `first()`, `last()`
- `mean()`, `median()`
- `min()`, `max()`
- `std()`, `var()`
- `mad()`
- `prod()`
- `sum()`

Aby móc wykonywać bardziej skomplikowane zapytania, musimy jednak połączyć agregacje z odpowiednim grupowaniem. Grupowanie polega na podzieleniu zbioru danych na mniejsze zbiory na podstawie unikalnych wartości w kolumnie po której grupujemy i wykonaniu danej agregacji. Wyniki agregacji są następnie łączone w nowy zbiór danych. Nie musimy jednak wykonywać tych operacji samodzielnie - służy do tego funkcja `groupby`.

In [113]:
df = pd.DataFrame(
    {
        'key' : ['A', 'B', 'C', 'A', 'B', 'C'],
        'data': range(0, 6),
        'data2': range(1, 7)
    },
    columns=['key', 'data', 'data2']
)

In [114]:
df

  key  data  data2
0   A     0      1
1   B     1      2
2   C     2      3
3   A     3      4
4   B     4      5
5   C     5      6

Wynik działania `groupby` to obiekt typu `DataFrameGroupBy`.

Na takim obiekcie możemy następnie wywołać funkcję agregująca która wykona wszystkie operacje potrzebne do obliczenia wyniku grupowania:

In [115]:
df.groupby('key')['data2'].agg(list)

key
A    [1, 4]
B    [2, 5]
C    [3, 6]
Name: data2, dtype: object

Co więcej obiekt typu `GroupBy` wspiera również indeksowanie:

In [ ]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [ ]:
 # Load the Iris flower dataset from the sklearn datasets module
from sklearn import datasets
iris = datasets.load_iris()

In [ ]:

# Convert the dataset into a Pandas DataFrame
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['type'] = pd.Series(iris.target)

In [ ]:
iris_df

In [ ]:
# Explore the dataset using Pandas functions
(iris_df.tail())

In [ ]:
print(iris_df.info())

In [ ]:
iris_df.describe()

In [ ]:
print(iris_df.isna().sum())

In [ ]:
# Clean the data by checking for and handling missing values
iris_df.dropna(inplace=True)

In [ ]:
iris_df

In [ ]:
# Sort the dataset by one or more columns
iris_df.sort_values(by=['type', 'petal length (cm)'], inplace=True)

In [ ]:
# Group the dataset by one or more columns
grouped_df = iris_df.groupby('type')

In [ ]:
# Calculate the mean, median, and standard deviation of the features
print(iris_df.mean())
print(iris_df.median())
print(iris_df.std())

In [ ]:
# Export the cleaned and transformed data to a new CSV file
iris_df.to_csv('iris_cleaned.csv',index=False)

In [ ]:
pd.read_csv('iris_cleaned.csv')

In [ ]:


# Save the descriptive statistics of the dataset to a new Excel file
stats_df = iris_df.describe()
stats_df.to_excel('iris_statistics.xlsx', index=False)

# Wyjaśnienie funkcji `.apply()` z użyciem `lambda` i operacji wektorowych w Pandas

## `.apply()` z `lambda`

Funkcja `.apply()` w Pandas pozwala na wykonywanie operacji na wierszach lub kolumnach DataFrame, gdzie logika obliczeń może być bardziej skomplikowana. Najczęściej używana z `lambda`, sprawdza się w sytuacjach, gdy potrzebujemy:

1. Zastosować niestandardowe obliczenia na poziomie wiersza lub kolumny.
2. Wykorzystać warunki lub złożoną logikę, np. różne wzory w zależności od wartości w jednej lub kilku kolumnach.


### Przykład:
Chcemy obliczyć nową kolumnę, w której:
- Jeśli wartość w kolumnie A jest większa niż w kolumnie B, wynik to `A^2 - 2 * B`.
- W przeciwnym razie wynik to `2 * B^2 + A`.

W takim przypadku `.apply()` z `lambda` pozwala na prostą i czytelną implementację tej logiki.

In [117]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 4, 3, 7],
    'B': [2, 2, 3, 6]
})

df['Wynik'] = df.apply(lambda row:
                           row['A']**2 - 2*row['B']
                           if row['A'] > row['B']
                           else 2*row['B']**2 + row['A'],
                       axis=1)

print(df)

   A  B  Wynik
0  1  2      9
1  4  2     12
2  3  3     21
3  7  6     37


---

## Operacje wektorowe

Operacje wektorowe w Pandas opierają się na bezpośrednich obliczeniach na całych kolumnach bez iteracji po wierszach. Są one:
- Szybsze, ponieważ korzystają z niskopoziomowych optymalizacji w NumPy.
- Bardziej wydajne w przypadku prostych operacji matematycznych, takich jak dodawanie, mnożenie czy zastosowanie jednego warunku.

### Przykład:
Chcemy obliczyć nową kolumnę, która zawsze jest równa `0.7 * A + 0.3 * B`. W takim przypadku możemy bez problemu wykonać operację wektorową na kolumnach A i B.

In [118]:
df['Wynik_wektorowo'] = 0.7 * df['A'] + 0.3 * df['B']

print(df)

   A  B  Wynik  Wynik_wektorowo
0  1  2      9              1.3
1  4  2     12              3.4
2  3  3     21              3.0
3  7  6     37              6.7

In [ ]:
from sklearn.datasets import load_wine
import pandas as pd

# Load the wine dataset and convert it to a Pandas DataFrame
data = load_wine(as_frame=True)
wine_df = data.frame

In [ ]:
wine_df

In [ ]:
# Vectorized calculation for Quality_Score
wine_df['Quality_Score'] = ((0.7 * wine_df['total_phenols'] + 0.3 * wine_df['flavanoids']) ** 2)

# Display the first few rows
print(wine_df[['total_phenols', 'flavanoids', 'Quality_Score']].head())

In [ ]:

# Define a function to classify alcohol levels
def classify_alcohol(content):
    if content < 12:
        return 'Low'
    elif 12 <= content <= 13.5:
        return 'Medium'
    else:
        return 'High'

In [ ]:

# Apply the function to the 'alcohol' column
wine_df['Alcohol_Level'] = wine_df['alcohol'].apply(classify_alcohol)

# Display the first few rows
print(wine_df[['alcohol', 'Alcohol_Level']].head())

In [ ]:
# Apply row-wise logic using a lambda function
wine_df['Complex_Score'] = wine_df.apply(
    lambda row: row['total_phenols']**2 - 2 * row['flavanoids']
    if row['total_phenols'] > row['flavanoids']
    else 2 * row['flavanoids']**2 + row['total_phenols'], axis=1
)



# Display the first few rows
print(wine_df[['total_phenols', 'flavanoids', 'Complex_Score']].head())

#### Zadania do zbioru Iris

##### 1. Znajdowanie liczby obserwacji i obiektów w zestawie danych przy użyciu atrybutu shape

In [ ]:

# Output: (150, 5)

##### 2. Przefiltruj zestaw danych, aby uwzględnić tylko obserwacje, w których długość płatka ( petal length )  jest większa niż szerokość płatka(petal width).

In [ ]:
# Output:  Only rows whe re petal length is greater than petal width

##### 3. Oblicz średnią, medianę i odchylenie standardowe szerokości platka (petal width) dla każdego gatunku kwiatu Iris za pomocą funkcji groupby().

In [ ]:
# Output: mean sepal width for each species
# Output: median sepal width for each species
# Output: standard deviation of sepal width for each species

##### 4. Utwórz nową kolumnę w zestawie danych, która oblicza stosunek długości płatka do szerokości płatka dla każdej obserwacji.

In [ ]:

# Output: New column petal length/width ratio

##### 5.Posortuj zestaw danych według kolumny długości płatków w kolejności malejącej i zresetuj indeks.

In [ ]:
# Output: Sorted dataset by petal length in descending order

## Ćwiczenia Pandas

Pełny zestaw ćwiczeń do wykorzystania na zajęciach lub po zajęciach.

# 📊 Opis Zbiorów Danych

## 1. **Better Life Index (2024)**
Ten zbiór danych zawiera informacje o jakości życia w różnych krajach. Zawiera 38 wierszy (po jednym na kraj) i 26 kolumn. Kluczowe cechy:
- **Country**: Nazwa kraju.
- **GDP per capita (USD)**: PKB na mieszkańca w dolarach amerykańskich.
- Różne metryki związane z mieszkaniem, edukacją, dochodami, zatrudnieniem, zdrowiem i bezpieczeństwem:
  - `Housing expenditure`, `Rooms per person`, `Household net wealth`.
  - `Life expectancy` (oczekiwana długość życia), `Self-reported health` (samoocena zdrowia), `Feeling safe walking alone at night` (poczucie bezpieczeństwa w nocy).
  - `Time devoted to leisure and personal care` (czas poświęcony na odpoczynek i sprawy osobiste).
- Niektóre kolumny mają brakujące wartości, np. `Time devoted to leisure and personal care` występuje tylko dla 22 krajów.

## 2. **Global Power Plant Database**
Ten zbiór danych zawiera informacje o elektrowniach na całym świecie. Zawiera 34 936 wierszy i 36 kolumn. Kluczowe cechy:
- **Country**: Skrócona i pełna nazwa kraju.
- **Name**: Nazwa elektrowni.
- **Capacity (MW)**: Moc w megawatach (MW).
- **Primary Fuel**: Główny rodzaj paliwa (np. Hydro, Solar).
- **Generation data (2013–2019)**: Dane dotyczące wytwarzania energii elektrycznej (rzeczywiste i szacowane) w gigawatogodzinach (GWh).
- Dane geograficzne, takie jak szerokość i długość geograficzna oraz źródło danych geolokalizacyjnych.
- Niektóre kolumny, takie jak `commissioning_year` (rok uruchomienia) i `owner` (właściciel), mają znaczące braki w danych.

## 3. **Electric Vehicle Population**
Ten zbiór danych zawiera informacje o pojazdach elektrycznych (EV) zarejestrowanych w wybranym regionie. Zawiera 181 458 wierszy i 17 kolumn. Kluczowe cechy:
- **VIN (1-10)**: Numer identyfikacyjny pojazdu.
- **Make** i **Model**: Producent i konkretny model pojazdu.
- **Electric Vehicle Type**: Typ pojazdu elektrycznego (np. Battery Electric Vehicle – BEV, Plug-in Hybrid Electric Vehicle – PHEV).
- **Electric Range**: Maksymalny zasięg pojazdu na pełnym ładowaniu.
- **Base MSRP**: Sugerowana cena detaliczna producenta.
- **Dane lokalizacyjne**: Informacje o hrabstwie, mieście, stanie oraz dokładna geolokalizacja.
- **Clean Alternative Fuel Vehicle Eligibility**: Informacja o zgodności pojazdu z przepisami dotyczącymi paliw alternatywnych.
- Zawiera także szczegółowe dane o dostawcach energii elektrycznej i lokalizacjach zasięgu EV.

Każdy zbiór danych dostarcza unikalnych informacji i może być wykorzystany do różnych analiz, takich jak porównania społeczno-ekonomiczne, efektywność elektrowni czy trendy adopcji pojazdów elektrycznych.

In [120]:
# Importowanie bibliotek
import pandas as pd
import matplotlib.pyplot as plt

# Ścieżki do plików CSV
better_life_index_path = "data/better-life-index-2024.csv"
power_plant_path = "data/power_plant_database_global.csv"
ev_population_path = "data/electric_vehicle_population_data.csv"

# Wczytanie plików CSV
better_life_index_df = pd.read_csv(better_life_index_path)
power_plant_df = pd.read_csv(power_plant_path, low_memory=False)
ev_population_df = pd.read_csv(ev_population_path)

# 📊 Zadania z datasetu Electric Vehicle Population

### **Część 1: Analiza podstawowa**


1. **Liczba unikalnych producentów i modeli**  
   Wyświetl liczbę unikalnych producentów pojazdów elektrycznych (`Make`) i unikalnych modeli (`Model`).  
   **Hint:** Użyj metody `.nunique()`.

#### Rozwiązanie

In [121]:
print('Unikalni producenci:', ev_population_df['Make'].nunique())
print('Unikalne modele:', ev_population_df['Model'].nunique())

Unikalni producenci: 40
Unikalne modele: 143


2. **Liczba pojazdów BEV i PHEV**  
   Policz liczbę pojazdów typu `Battery Electric Vehicle (BEV)` i `Plug-in Hybrid Electric Vehicle (PHEV)`.  
   **Hint:** Użyj metody `.value_counts()` na kolumnie `Electric Vehicle Type`.

#### Rozwiązanie

In [122]:
ev_population_df['Electric Vehicle Type'].value_counts()

Electric Vehicle Type
Battery Electric Vehicle (BEV)            141973
Plug-in Hybrid Electric Vehicle (PHEV)     39485
Name: count, dtype: int64

3. **Statystyki zasięgu**  
   Znajdź średni, minimalny i maksymalny zasięg (`Electric Range`) pojazdów elektrycznych.  
   **Hint:** Użyj metody `.describe()` lub poszczególnych funkcji takich jak `.mean()`, `.min()`, `.max()`.

#### Rozwiązanie

In [123]:
ev_population_df['Electric Range'].agg(['mean', 'min', 'max'])

mean     57.826665
min       0.000000
max     337.000000
Name: Electric Range, dtype: float64

4. **5 pojazdów o największym zasięgu**  
   Wyświetl 5 pojazdów o największym zasięgu (`Electric Range`).  
   **Hint:** Skorzystaj z funkcji `.nlargest()`.

#### Rozwiązanie

In [124]:
ev_population_df.nlargest(5, 'Electric Range')[['Make', 'Model', 'Model Year', 'Electric Range', 'Base MSRP']]

        Make    Model  Model Year  Electric Range  Base MSRP
2321   TESLA  MODEL S        2020             337          0
4232   TESLA  MODEL S        2020             337          0
5995   TESLA  MODEL S        2020             337          0
7255   TESLA  MODEL S        2020             337          0
15390  TESLA  MODEL S        2020             337          0


5. **Najpopularniejsze modele**  
   Wyświetl 5 modeli pojazdów elektrycznych, które najczęściej występują w danych.  
   **Hint:** Użyj metody `.value_counts()` na kolumnie `Model`.

#### Rozwiązanie

In [125]:
ev_population_df['Model'].value_counts().head(5)

Model
MODEL Y    37007
MODEL 3    30150
LEAF       13356
MODEL S     7731
BOLT EV     6935
Name: count, dtype: int64


---

### **Część 2: Filtrowanie i grupowanie danych**

6. **Pojazdy w stanie WA z zasięgiem > 200**  
   Znajdź pojazdy wyprodukowane w stanie `WA`, które mają zasięg większy niż 200 mil.  
   **Hint:** Użyj operatorów logicznych (`&`) oraz filtrowania na DataFrame.

#### Rozwiązanie

In [126]:
ev_population_df.loc[
    (ev_population_df['State'] == 'WA') & (ev_population_df['Electric Range'] > 200),
    ['State', 'Make', 'Model', 'Model Year', 'Electric Range']
].head(20)

   State       Make    Model  Model Year  Electric Range
2     WA      TESLA  MODEL S        2017             210
4     WA      TESLA  MODEL 3        2020             308
7     WA      TESLA  MODEL 3        2020             322
10    WA  CHEVROLET  BOLT EV        2018             238
11    WA      TESLA  MODEL S        2015             208
15    WA      TESLA  MODEL 3        2020             322
16    WA      TESLA  MODEL S        2017             210
23    WA  CHEVROLET  BOLT EV        2020             259
25    WA  CHEVROLET  BOLT EV        2019             238
26    WA  CHEVROLET  BOLT EV        2017             238
31    WA       AUDI   E-TRON        2019             204
32    WA      TESLA  MODEL X        2020             293
33    WA      TESLA  MODEL X        2018             238
38    WA      TESLA  MODEL 3        2020             322
39    WA        KIA     NIRO        2020             239
47    WA      TESLA  MODEL 3        2018             215
52    WA      TESLA  MODEL 3        2019             220
53    WA      TESLA  MODEL X        2018             238
54    WA      TESLA  MODEL X        2018             238
60    WA  CHEVROLET  BOLT EV        2020             259


7. **Średni zasięg dla każdego typu pojazdu**  
   Oblicz średni zasięg (`Electric Range`) dla każdego typu pojazdu elektrycznego (`Electric Vehicle Type`).  
   **Hint:** Użyj metody `.groupby()` i `.mean()`.

#### Rozwiązanie

In [ ]:
ev_population_df.groupby('Electric Vehicle Type')['Electric Range'].mean().sort_values(ascending=False)



8. **Liczba pojazdów w każdym stanie**  
   Wyświetl liczbę pojazdów elektrycznych w każdym stanie (`State`).  
   **Hint:** Użyj metody `.value_counts()`.

#### Rozwiązanie

In [ ]:
ev_population_df['State'].value_counts()

9. **Średni zasięg dla każdego producenta**  
   Grupuj dane według `Make` i oblicz średni zasięg pojazdów każdego producenta.  
   **Hint:** Użyj metody `.groupby()` i `.mean()`.

#### Rozwiązanie

In [ ]:
ev_population_df.groupby('Make')['Electric Range'].mean().sort_values(ascending=False)


### **Część 3: Tworzenie nowych kolumn**

10. **Efektywność zasięgu**  
    Dodaj nową kolumnę `Range Efficiency`, która jest stosunkiem `Electric Range` do `Base MSRP` (w tysiącach dolarów).  
    **Hint:** Operacje na DataFrame można wykonać przez podział kolumn.

#### Rozwiązanie

In [ ]:
base_msrp = ev_population_df['Base MSRP'].where(ev_population_df['Base MSRP'] > 0)
ev_population_df['Range Efficiency'] = ev_population_df['Electric Range'] / (base_msrp / 1000)
ev_population_df[['Make', 'Model', 'Electric Range', 'Base MSRP', 'Range Efficiency']].head()

11. **Najbardziej efektywne pojazdy**  
    Znajdź 5 pojazdów o najwyższej efektywności (`Range Efficiency`).  
    **Hint:** Użyj funkcji `.nlargest()` na nowej kolumnie.

#### Rozwiązanie

In [ ]:
ev_population_df.dropna(subset=['Range Efficiency']).nlargest(
    5, 'Range Efficiency'
)[['Make', 'Model', 'Electric Range', 'Base MSRP', 'Range Efficiency']]

### **Część 4: Wizualizacje**

12. **Histogram zasięgu**  
    Stwórz histogram przedstawiający rozkład zasięgu (`Electric Range`) pojazdów elektrycznych.  
    **Hint:** Użyj funkcji `plt.hist()` z Matplotlib.

#### Rozwiązanie

In [ ]:
plt.figure(figsize=(8, 4))
plt.hist(ev_population_df['Electric Range'].dropna(), bins=30, color='steelblue', edgecolor='black')
plt.title('Rozkład zasięgu pojazdów elektrycznych')
plt.xlabel('Electric Range')
plt.ylabel('Liczba pojazdów')
plt.tight_layout()
plt.show()

13. **Średni zasięg dla każdego typu**  
    Stwórz wykres słupkowy, który pokazuje średni zasięg dla każdego typu pojazdu (`Electric Vehicle Type`).  
    **Hint:** Użyj `groupby()` i wykresu słupkowego w `matplotlib` lub `pandas`.

#### Rozwiązanie

In [ ]:
mean_range_by_type = ev_population_df.groupby('Electric Vehicle Type')['Electric Range'].mean().sort_values(ascending=False)
plt.figure(figsize=(8, 4))
mean_range_by_type.plot(kind='bar', color='teal')
plt.title('Średni zasięg dla każdego typu pojazdu')
plt.xlabel('Electric Vehicle Type')
plt.ylabel('Średni Electric Range')
plt.xticks(rotation=15, ha='right')
plt.tight_layout()
plt.show()

14. **Scatterplot z Base MSRP a Electric Range**  
    Narysuj wykres `scatterplot`, który pokazuje zależność między `Base MSRP` a `Electric Range`, z podziałem na typ pojazdu (`hue=Electric Vehicle Type`).  
    **Hint:** Użyj `plt.scatter()` albo `DataFrame.plot.scatter()`.

#### Rozwiązanie

In [ ]:
plt.figure(figsize=(8, 5))
plot_df = ev_population_df[['Base MSRP', 'Electric Range', 'Electric Vehicle Type']].dropna()
plot_df = plot_df.sample(min(len(plot_df), 5000), random_state=42)
for vehicle_type, group in plot_df.groupby('Electric Vehicle Type'):
    plt.scatter(group['Base MSRP'], group['Electric Range'], label=vehicle_type, alpha=0.5, s=20)
plt.title('Base MSRP vs Electric Range')
plt.xlabel('Base MSRP')
plt.ylabel('Electric Range')
plt.legend()
plt.tight_layout()
plt.show()

15. **Boxplot z zasięgu dla producentów**  
    Stwórz wykres `boxplot`, przedstawiający rozkład zasięgu (`Electric Range`) dla różnych producentów (`Make`).  
    **Hint:** Użyj `plt.boxplot()` i wybierz najbardziej popularnych producentów (`.value_counts()` na kolumnie `Make`).

#### Rozwiązanie

In [ ]:
top_makes = ev_population_df['Make'].value_counts().head(5).index
boxplot_data = [
    ev_population_df.loc[ev_population_df['Make'] == make, 'Electric Range'].dropna()
    for make in top_makes
]
plt.figure(figsize=(9, 5))
plt.boxplot(boxplot_data, tick_labels=top_makes)
plt.title('Rozkład zasięgu dla najpopularniejszych producentów')
plt.xlabel('Make')
plt.ylabel('Electric Range')
plt.xticks(rotation=20, ha='right')
plt.tight_layout()
plt.show()

# 📊 Zadania z datasetu Global Power Plant Database

### **Część 1: Analiza podstawowa**


1. Wyświetl liczbę unikalnych krajów (`country`) i unikalnych rodzajów paliw (`primary_fuel`).

#### Rozwiązanie

In [ ]:
print('Liczba unikalnych krajów:', power_plant_df['country'].nunique())
print('Liczba unikalnych rodzajów paliw:', power_plant_df['primary_fuel'].nunique())

2. Oblicz średnią, minimalną i maksymalną moc (`capacity_mw`) elektrowni.

#### Rozwiązanie

In [ ]:
power_plant_df['capacity_mw'].agg(['mean', 'min', 'max'])

3. Policz liczbę elektrowni dla każdego rodzaju paliwa (`primary_fuel`).

#### Rozwiązanie

In [ ]:
power_plant_df['primary_fuel'].value_counts()

4. Znajdź 10 największych elektrowni pod względem mocy (`capacity_mw`).

#### Rozwiązanie

In [ ]:
power_plant_df.nlargest(10, 'capacity_mw')[['country_long', 'name', 'primary_fuel', 'capacity_mw']]

5. Wyświetl 5 krajów z największą całkowitą mocą zainstalowaną (`capacity_mw`).

#### Rozwiązanie

In [ ]:
power_plant_df.groupby('country_long')['capacity_mw'].sum().sort_values(ascending=False).head(5)

### **Część 2: Filtrowanie i grupowanie danych**

6. Wyświetl wszystkie elektrownie uruchomione po roku 2000, które mają moc większą niż 1000 MW.

#### Rozwiązanie

In [ ]:
power_plant_df.loc[
    (power_plant_df['commissioning_year'] > 2000) & (power_plant_df['capacity_mw'] > 1000),
    ['country_long', 'name', 'commissioning_year', 'capacity_mw', 'primary_fuel']
].sort_values(['commissioning_year', 'capacity_mw'], ascending=[False, False])

7. Oblicz średnią moc elektrowni (`capacity_mw`) dla każdego rodzaju paliwa (`primary_fuel`).

#### Rozwiązanie

In [ ]:
power_plant_df.groupby('primary_fuel')['capacity_mw'].mean().sort_values(ascending=False)

8. Policz liczbę elektrowni odnawialnych (Hydro, Solar, Wind, Geothermal) i nieodnawialnych w każdym kraju.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
country_counts = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby(['country_long', 'Renewable'])
    .size()
    .unstack(fill_value=0)
    .rename(columns={True: 'renewable_count', False: 'nonrenewable_count'})
)
country_counts.head(20)


9. Wyświetl kraje, które mają więcej elektrowni odnawialnych niż nieodnawialnych.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
country_counts = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby(['country_long', 'Renewable'])
    .size()
    .unstack(fill_value=0)
    .rename(columns={True: 'renewable_count', False: 'nonrenewable_count'})
)
country_counts.loc[country_counts['renewable_count'] > country_counts['nonrenewable_count']]

### **Część 3: Tworzenie nowych kolumn**

10. Dodaj nową kolumnę `Renewable`, która przyjmuje wartość `True` dla odnawialnych źródeł energii (Hydro, Solar, Wind, Geothermal) i `False` dla pozostałych.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
power_plant_df['Renewable'] = power_plant_df['primary_fuel'].isin(renewable_fuels)
power_plant_df[['primary_fuel', 'Renewable']].head()

11. Dodaj nową kolumnę `Age`, która oblicza wiek elektrowni (rok 2024 - `commissioning_year`).

#### Rozwiązanie

In [ ]:
power_plant_df['Age'] = 2024 - power_plant_df['commissioning_year']
power_plant_df[['name', 'commissioning_year', 'Age']].head()

### **Część 4: Wizualizacje**

12. Stwórz histogram (Matplotlib) pokazujący rozkład mocy (`capacity_mw`) elektrowni.

#### Rozwiązanie

In [ ]:
plt.figure(figsize=(8, 4))
plt.hist(power_plant_df['capacity_mw'].dropna(), bins=40, color='slateblue', edgecolor='black')
plt.title('Rozkład mocy elektrowni')
plt.xlabel('capacity_mw')
plt.ylabel('Liczba elektrowni')
plt.tight_layout()
plt.show()

13. Stwórz wykres słupkowy przedstawiający średnią moc elektrowni dla każdego rodzaju paliwa (`primary_fuel`) przy użyciu `matplotlib` lub `pandas`.

#### Rozwiązanie

In [ ]:
mean_capacity_by_fuel = power_plant_df.groupby('primary_fuel')['capacity_mw'].mean().sort_values(ascending=False)
plt.figure(figsize=(10, 5))
mean_capacity_by_fuel.plot(kind='bar', color='darkorange')
plt.title('Średnia moc elektrowni dla każdego rodzaju paliwa')
plt.xlabel('primary_fuel')
plt.ylabel('Średnia capacity_mw')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

14. Narysuj wykres punktowy pokazujący zależność między `capacity_mw` a `generation_gwh_2019` z rozróżnieniem rodzajów paliwa (`primary_fuel`) przy użyciu `matplotlib`.

#### Rozwiązanie

In [ ]:
plt.figure(figsize=(8, 5))
plot_df = power_plant_df[['capacity_mw', 'generation_gwh_2019', 'primary_fuel']].dropna()
top_fuels = plot_df['primary_fuel'].value_counts().head(6).index
plot_df = plot_df[plot_df['primary_fuel'].isin(top_fuels)]
for fuel, group in plot_df.groupby('primary_fuel'):
    plt.scatter(group['capacity_mw'], group['generation_gwh_2019'], label=fuel, alpha=0.5, s=20)
plt.title('capacity_mw vs generation_gwh_2019')
plt.xlabel('capacity_mw')
plt.ylabel('generation_gwh_2019')
plt.legend()
plt.tight_layout()
plt.show()


15. Stwórz wykres `boxplot` pokazujący rozkład mocy (`capacity_mw`) dla odnawialnych i nieodnawialnych źródeł energii przy użyciu `matplotlib`.

---

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
plot_df = power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
boxplot_data = [
    plot_df.loc[plot_df['Renewable'], 'capacity_mw'].dropna(),
    plot_df.loc[~plot_df['Renewable'], 'capacity_mw'].dropna(),
]
plt.figure(figsize=(7, 5))
plt.boxplot(boxplot_data, tick_labels=['Renewable', 'Nonrenewable'])
plt.title('Rozkład mocy dla źródeł odnawialnych i nieodnawialnych')
plt.ylabel('capacity_mw')
plt.tight_layout()
plt.show()

### **Część 5: Zaawansowane analizy**

16. Znajdź korelację między `capacity_mw` a generacją energii (`generation_gwh_2019`) i zinterpretuj wynik.

#### Rozwiązanie

In [ ]:
corr_value = power_plant_df[['capacity_mw', 'generation_gwh_2019']].dropna().corr().loc['capacity_mw', 'generation_gwh_2019']
print('Korelacja capacity_mw vs generation_gwh_2019:', corr_value)
if corr_value > 0.7:
    print('Interpretacja: silna dodatnia zależność.')
elif corr_value > 0.3:
    print('Interpretacja: umiarkowana dodatnia zależność.')
elif corr_value > 0:
    print('Interpretacja: słaba dodatnia zależność.')
else:
    print('Interpretacja: brak dodatniej zależności lub zależność ujemna.')

17. Oblicz całkowitą generację energii odnawialnej (Solar, Wind, Hydro, Geothermal) w roku 2019 i porównaj ją z generacją nieodnawialną.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
generation_summary = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('Renewable')['generation_gwh_2019']
    .sum(min_count=1)
    .rename(index={True: 'renewable_generation_gwh_2019', False: 'nonrenewable_generation_gwh_2019'})
)
generation_summary

18. Wyświetl 10 krajów o największej średniej mocy odnawialnych elektrowni.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
(
    power_plant_df[power_plant_df['primary_fuel'].isin(renewable_fuels)]
    .groupby('country_long')['capacity_mw']
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

19. Stwórz `heatmap` przedstawiający korelację między wartościami numerycznymi (np. `capacity_mw`, `generation_gwh_2019`, `commissioning_year`).

#### Rozwiązanie

In [ ]:
corr = power_plant_df[['capacity_mw', 'generation_gwh_2019', 'commissioning_year']].dropna().corr()
plt.figure(figsize=(6, 5))
plt.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
plt.xticks(range(len(corr.columns)), corr.columns, rotation=45, ha='right')
plt.yticks(range(len(corr.index)), corr.index)
plt.colorbar(label='Korelacja')
plt.title('Heatmap korelacji - Global Power Plant Database')
plt.tight_layout()
plt.show()
corr

# 📊 Zadania z datasetu Better Life Index

### **Część 1: Analiza podstawowa**

1. **Liczba krajów w zbiorze danych**  
   Wyświetl liczbę unikalnych krajów w zbiorze danych (`Country`).  
   **Hint:** Użyj metody `.nunique()` na kolumnie `Country`.

#### Rozwiązanie

In [ ]:
better_life_index_df['Country'].nunique()


2. **Średni wskaźnik `Life satisfaction`**  
   Policz średnią wartość wskaźnika `Life satisfaction` dla wszystkich krajów.  
   **Hint:** Użyj metody `.mean()` na kolumnie `Life satisfaction`.

#### Rozwiązanie

In [ ]:
better_life_index_df['Life satisfaction'].mean()

3. **5 krajów z najwyższym wskaźnikiem `Life satisfaction`**  
   Wyświetl 5 krajów z najwyższym wskaźnikiem `Life satisfaction`.  
   **Hint:** Użyj funkcji `.nlargest(5)`.

#### Rozwiązanie

In [ ]:
better_life_index_df.nlargest(5, 'Life satisfaction')[['Country', 'Life satisfaction']]


4. **5 krajów z najniższym `GDP per capita (USD)`**  
   Wyświetl 5 krajów z najniższym wskaźnikiem `GDP per capita (USD)`.  
   **Hint:** Użyj funkcji `.nsmallest(5)`.

#### Rozwiązanie

In [ ]:
better_life_index_df.nsmallest(5, 'GDP per capita (USD)')[['Country', 'GDP per capita (USD)']]

5. **Średnia i mediana długości życia (`Life expectancy`)**  
   Oblicz średnią i medianę długości życia dla wszystkich krajów.  
   **Hint:** Użyj metody `.mean()` i `.median()` na kolumnie `Life expectancy`.

#### Rozwiązanie

In [ ]:
print('Średnia:', better_life_index_df['Life expectancy'].mean())
print('Mediana:', better_life_index_df['Life expectancy'].median())

### **Część 2: Filtrowanie i grupowanie danych**

6. **Kraje z `Rooms per person` > 2**  
   Znajdź kraje, w których wskaźnik `Rooms per person` jest większy niż 2.  
   **Hint:** Użyj filtrowania z operatorem warunkowym (`>`) na kolumnie `Rooms per person`.

#### Rozwiązanie

In [ ]:
better_life_index_df.loc[
    better_life_index_df['Rooms per person'] > 2,
    ['Country', 'Rooms per person']
]

7. **Średni `GDP per capita (USD)` dla krajów z wysokim `Life satisfaction`**  
   Oblicz średnią wartość `GDP per capita (USD)` dla krajów, w których wskaźnik `Life satisfaction` wynosi więcej niż 7.  
   **Hint:** Użyj filtrowania oraz metody `.mean()`.

#### Rozwiązanie

In [ ]:
better_life_index_df.loc[
    better_life_index_df['Life satisfaction'] > 7,
    'GDP per capita (USD)'
].mean()

8. **Średnia długość życia dla grup `Life satisfaction`**  
   Grupuj dane według zaokrąglonych wartości `Life satisfaction` i oblicz średnią długość życia (`Life expectancy`) dla każdej grupy.  
   **Hint:** Użyj metody `.groupby()` oraz `.mean()` na zaokrąglonej kolumnie `Life satisfaction`.

#### Rozwiązanie

In [ ]:
(
    better_life_index_df.assign(Life_satisfaction_group=better_life_index_df['Life satisfaction'].round())
    .groupby('Life_satisfaction_group')['Life expectancy']
    .mean()
)


9. **Kraje z dużą ilością czasu na odpoczynek**  
   Policz liczbę krajów, w których `Time devoted to leisure and personal care` przekracza 15 godzin.  
   **Hint:** Użyj filtrowania z operatorem warunkowym (`>`) oraz metody `.count()`.

#### Rozwiązanie

In [ ]:
(better_life_index_df['Time devoted to leisure and personal care'] > 15).sum()

### **Część 3: Tworzenie nowych kolumn**


10. **Dodanie kolumny `Health Index`**  
    Dodaj nową kolumnę `Health Index`, będącą średnią `Life expectancy` i `Self-reported health`.  
    **Hint:** Użyj wyrażenia `DataFrame[["Column1", "Column2"]].mean(axis=1)`.

#### Rozwiązanie

In [ ]:
better_life_index_df['Health Index'] = better_life_index_df[['Life expectancy', 'Self-reported health']].mean(axis=1)
better_life_index_df[['Country', 'Life expectancy', 'Self-reported health', 'Health Index']].head()


11. **Stworzenie kolumny `Safety Score`**  
    Dodaj kolumnę `Safety Score`, obliczaną jako różnica między `Feeling safe walking alone at night` a `Homicide rate`.  
    **Hint:** Wykonaj operację odejmowania między odpowiednimi kolumnami.

#### Rozwiązanie

In [ ]:
better_life_index_df['Safety Score'] = (
    better_life_index_df['Feeling safe walking alone at night'] - better_life_index_df['Homicide rate']
)
better_life_index_df[['Country', 'Feeling safe walking alone at night', 'Homicide rate', 'Safety Score']].head()

### **Część 4: Wizualizacje**

12. **Histogram `Life satisfaction`**  
    Stwórz histogram przedstawiający rozkład wartości `Life satisfaction`.  
    **Hint:** Użyj funkcji `plt.hist()` z Matplotlib.

#### Rozwiązanie

In [ ]:
plt.figure(figsize=(8, 4))
plt.hist(better_life_index_df['Life satisfaction'].dropna(), bins=15, color='mediumseagreen', edgecolor='black')
plt.title('Rozkład Life satisfaction')
plt.xlabel('Life satisfaction')
plt.ylabel('Liczba krajów')
plt.tight_layout()
plt.show()


13. **Średnia długość życia dla krajów z najwyższym `GDP per capita (USD)`**  
    Stwórz wykres słupkowy, pokazujący średnią długość życia (`Life expectancy`) dla 10 krajów o najwyższym `GDP per capita (USD)`.  
    **Hint:** Użyj `.nlargest(10)` oraz wykresu słupkowego w `matplotlib` lub `pandas`.

#### Rozwiązanie

In [ ]:
top10_gdp = better_life_index_df.nlargest(10, 'GDP per capita (USD)').sort_values('GDP per capita (USD)')
plt.figure(figsize=(9, 5))
plt.barh(top10_gdp['Country'], top10_gdp['Life expectancy'], color='cornflowerblue')
plt.title('Life expectancy dla 10 krajów o najwyższym GDP per capita')
plt.xlabel('Life expectancy')
plt.ylabel('Country')
plt.tight_layout()
plt.show()

14. **Scatterplot: `GDP per capita (USD)` vs `Life satisfaction`**  
    Narysuj `scatterplot` pokazujący zależność między `GDP per capita (USD)` a `Life satisfaction`.  
    **Hint:** Użyj `plt.scatter()` albo `DataFrame.plot.scatter()`.

#### Rozwiązanie

In [ ]:
plt.figure(figsize=(8, 5))
plt.scatter(better_life_index_df['GDP per capita (USD)'], better_life_index_df['Life satisfaction'], alpha=0.7)
plt.title('GDP per capita (USD) vs Life satisfaction')
plt.xlabel('GDP per capita (USD)')
plt.ylabel('Life satisfaction')
plt.tight_layout()
plt.show()


15. **Heatmap korelacji**  
    Stwórz `heatmap`, przedstawiającą korelacje między wszystkimi zmiennymi numerycznymi w zbiorze danych.  
    **Hint:** Użyj `df.corr()` oraz `plt.imshow()` lub `matshow()` z odpowiednimi parametrami.

#### Rozwiązanie

In [ ]:
corr = better_life_index_df.select_dtypes(include='number').corr()
plt.figure(figsize=(10, 8))
plt.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1, aspect='auto')
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.index)), corr.index)
plt.colorbar(label='Korelacja')
plt.title('Heatmap korelacji - Better Life Index')
plt.tight_layout()
plt.show()
corr

# 📊 Zadania na połączonych danych Better Life Index i Global Power Plant Database


### **Część 1: Łączenie danych**

1. **Znajdź wspólne kraje**  
   Znajdź listę krajów, które występują w obu zbiorach danych: `Better Life Index` (`Country`) i `Global Power Plant Database` (`country_long`).  
   **Hint:** Użyj operacji zbiorów (`intersection`).

#### Rozwiązanie

In [ ]:
common_countries = sorted(
    set(better_life_index_df['Country']).intersection(power_plant_df['country_long'].dropna())
)
common_countries

2. **Zagreguj dane o elektrowniach**  
   Dla każdego kraju w zbiorze `Global Power Plant Database` oblicz:
   - `total_capacity_mw`: Suma mocy elektrowni.
   - `avg_capacity_mw`: Średnia moc elektrowni.
   - `renewable_count`: Liczba elektrowni odnawialnych (Hydro, Solar, Wind, Geothermal).
   - `nonrenewable_count`: Liczba elektrowni nieodnawialnych (pozostałe).  
   **Hint:** Użyj metody `.groupby()` i funkcji agregujących.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        total_capacity_mw=('capacity_mw', 'sum'),
        avg_capacity_mw=('capacity_mw', 'mean'),
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
    .reset_index()
)
agg_df.head()

3. **Połącz dane o krajach**  
   Połącz dane z `Better Life Index` i zagregowane dane z `Global Power Plant Database`, dopasowując kraje.  
   **Hint:** Użyj metody `pd.merge()` z kluczami `Country` i `country_long`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        total_capacity_mw=('capacity_mw', 'sum'),
        avg_capacity_mw=('capacity_mw', 'mean'),
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
    .reset_index()
)
merged_df = pd.merge(better_life_index_df, agg_df, left_on='Country', right_on='country_long', how='inner')
merged_df.head()

### **Część 2: Analiza podstawowa**


4. **Statystyki mocy elektrowni**  
   Policz średnią, minimalną i maksymalną wartość `total_capacity_mw` dla wszystkich krajów.  
   **Hint:** Użyj metod `.mean()`, `.min()` i `.max()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(total_capacity_mw=('capacity_mw', 'sum'))
    .reset_index()
)
agg_df['total_capacity_mw'].agg(['mean', 'min', 'max'])



5. **Średnia liczba elektrowni**  
   Oblicz średnią liczbę odnawialnych (`renewable_count`) i nieodnawialnych (`nonrenewable_count`) elektrowni na kraj.  
   **Hint:** Użyj metod `.mean()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
    .reset_index()
)
agg_df[['renewable_count', 'nonrenewable_count']].mean()

6. **5 krajów z największym udziałem odnawialnych elektrowni**  
   Znajdź 5 krajów, w których udział odnawialnych elektrowni (stosunek `renewable_count` do sumy wszystkich elektrowni) jest największy.  
   **Hint:** Oblicz udział jako `renewable_count / (renewable_count + nonrenewable_count)`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
    .reset_index()
)
agg_df['renewable_share'] = agg_df['renewable_count'] / (agg_df['renewable_count'] + agg_df['nonrenewable_count'])
agg_df.nlargest(5, 'renewable_share')[['country_long', 'renewable_share', 'renewable_count', 'nonrenewable_count']]

7. **5 krajów z najniższą średnią mocą elektrowni**  
   Wyświetl 5 krajów z najniższą wartością `avg_capacity_mw`.  
   **Hint:** Użyj funkcji `.nsmallest()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(avg_capacity_mw=('capacity_mw', 'mean'))
    .reset_index()
)
agg_df.nsmallest(5, 'avg_capacity_mw')

### **Część 3: Zależności między jakością życia a energetyką**

8. **Life satisfaction a udział odnawialnych elektrowni**  
   Oblicz korelację między `Life satisfaction` a udziałem odnawialnych elektrowni (`renewable_count / (renewable_count + nonrenewable_count)`).  
   **Hint:** Użyj metody `.corr()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        total_capacity_mw=('capacity_mw', 'sum'),
        avg_capacity_mw=('capacity_mw', 'mean'),
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
    .reset_index()
)
merged_df = pd.merge(better_life_index_df, agg_df, left_on='Country', right_on='country_long', how='inner')
merged_df['renewable_share'] = merged_df['renewable_count'] / (merged_df['renewable_count'] + merged_df['nonrenewable_count'])
merged_df[['Life satisfaction', 'renewable_share']].corr().loc['Life satisfaction', 'renewable_share']


9. **Life expectancy a moc odnawialnych elektrowni**  
   Oblicz średnią wartość `total_capacity_mw` dla krajów z `Life expectancy` powyżej i poniżej średniej.  
   **Hint:** Użyj filtrowania i funkcji `.mean()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(total_capacity_mw=('capacity_mw', 'sum'))
    .reset_index()
)
merged_df = pd.merge(better_life_index_df, agg_df, left_on='Country', right_on='country_long', how='inner')
mean_life_expectancy = merged_df['Life expectancy'].mean()
(
    merged_df.assign(
        life_expectancy_group=merged_df['Life expectancy'].apply(
            lambda x: 'powyżej średniej' if x > mean_life_expectancy else 'poniżej lub równa średniej'
        )
    )
    .groupby('life_expectancy_group')['total_capacity_mw']
    .mean()
)



10. **GDP per capita a całkowita moc elektrowni**  
    Narysuj wykres wykres punktowy, który pokazuje zależność między `GDP per capita (USD)` a `total_capacity_mw`.  
    **Hint:** Użyj `plt.scatter()` albo `DataFrame.plot.scatter()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(total_capacity_mw=('capacity_mw', 'sum'))
    .reset_index()
)
merged_df = pd.merge(better_life_index_df, agg_df, left_on='Country', right_on='country_long', how='inner')
plt.figure(figsize=(8, 5))
plt.scatter(merged_df['GDP per capita (USD)'], merged_df['total_capacity_mw'], alpha=0.7)
plt.title('GDP per capita (USD) vs total_capacity_mw')
plt.xlabel('GDP per capita (USD)')
plt.ylabel('total_capacity_mw')
plt.tight_layout()
plt.show()

### **Część 4: Wizualizacje**


11. **Histogram mocy elektrowni**  
    Narysuj histogram przedstawiający rozkład `total_capacity_mw` w krajach.  
    **Hint:** Użyj `plt.hist()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(total_capacity_mw=('capacity_mw', 'sum'))
    .reset_index()
)
plt.figure(figsize=(8, 4))
plt.hist(agg_df['total_capacity_mw'].dropna(), bins=20, color='indianred', edgecolor='black')
plt.title('Rozkład total_capacity_mw')
plt.xlabel('total_capacity_mw')
plt.ylabel('Liczba krajów')
plt.tight_layout()
plt.show()


12. **Wykres słupkowy: Renewable vs Nonrenewable**  
    Narysuj wykres słupkowy, który pokazuje średnią liczbę odnawialnych i nieodnawialnych elektrowni na kraj.  
    **Hint:** Użyj `matplotlib` lub `pandas`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
)
mean_counts = agg_df[['renewable_count', 'nonrenewable_count']].mean()
plt.figure(figsize=(6, 4))
mean_counts.plot(kind='bar', color=['forestgreen', 'gray'])
plt.title('Średnia liczba elektrowni na kraj')
plt.ylabel('Średnia liczba elektrowni')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()



13. **Heatmap korelacji**  
    Stwórz `heatmap`, która przedstawia korelacje między zmiennymi numerycznymi: `Life satisfaction`, `GDP per capita (USD)`, `total_capacity_mw`, `renewable_count`.  
    **Hint:** Użyj `plt.imshow()` albo `matshow()`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        total_capacity_mw=('capacity_mw', 'sum'),
        renewable_count=('Renewable', 'sum'),
    )
    .reset_index()
)
merged_df = pd.merge(better_life_index_df, agg_df, left_on='Country', right_on='country_long', how='inner')
corr = merged_df[['Life satisfaction', 'GDP per capita (USD)', 'total_capacity_mw', 'renewable_count']].corr()
plt.figure(figsize=(7, 5))
plt.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
plt.xticks(range(len(corr.columns)), corr.columns, rotation=45, ha='right')
plt.yticks(range(len(corr.index)), corr.index)
plt.colorbar(label='Korelacja')
plt.title('Heatmap korelacji - jakość życia i energetyka')
plt.tight_layout()
plt.show()
corr



14. **Top 10 krajów z odnawialnymi elektrowniami**  
    Stwórz wykres słupkowy przedstawiający 10 krajów z najwyższą liczbą odnawialnych elektrowni (`renewable_count`).  
    **Hint:** Użyj funkcji `.nlargest()` i wykresu słupkowego w `matplotlib` lub `pandas`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(renewable_count=('Renewable', 'sum'))
    .reset_index()
)
top10 = agg_df.nlargest(10, 'renewable_count').sort_values('renewable_count')
plt.figure(figsize=(9, 5))
plt.barh(top10['country_long'], top10['renewable_count'], color='seagreen')
plt.title('Top 10 krajów z największą liczbą odnawialnych elektrowni')
plt.xlabel('renewable_count')
plt.ylabel('country_long')
plt.tight_layout()
plt.show()


15. **Rozkład odnawialnych i nieodnawialnych elektrowni**  
    Stwórz wykres `boxplot`, który pokazuje rozkład `total_capacity_mw` dla krajów z przewagą odnawialnych i nieodnawialnych elektrowni.  
    **Hint:** Użyj `plt.boxplot()` i stwórz kategorię na podstawie `renewable_count > nonrenewable_count`.

#### Rozwiązanie

In [ ]:
renewable_fuels = ['Hydro', 'Solar', 'Wind', 'Geothermal']
agg_df = (
    power_plant_df.assign(Renewable=power_plant_df['primary_fuel'].isin(renewable_fuels))
    .groupby('country_long')
    .agg(
        total_capacity_mw=('capacity_mw', 'sum'),
        renewable_count=('Renewable', 'sum'),
        nonrenewable_count=('Renewable', lambda x: (~x).sum()),
    )
    .reset_index()
)
plot_df = agg_df.assign(
    dominant_source=agg_df['renewable_count'] > agg_df['nonrenewable_count']
)
boxplot_data = [
    plot_df.loc[plot_df['dominant_source'], 'total_capacity_mw'].dropna(),
    plot_df.loc[~plot_df['dominant_source'], 'total_capacity_mw'].dropna(),
]

plt.figure(figsize=(7, 5))
plt.boxplot(
    boxplot_data,
    tick_labels=['Przewaga odnawialnych', 'Przewaga nieodnawialnych']
)
plt.title('Rozkład total_capacity_mw według dominującego typu elektrowni')
plt.ylabel('total_capacity_mw')
plt.tight_layout()
plt.show()